### ISSUE TITLE
Add all local street names to suggestions

### ISSUE THREAD

**Issue by skjerns** [leih-lokal/LeihLokalVerwaltung#106]
I think it would be useful to make the streetname searchable, so that it suggests streets that are already in the database. Even nicer would be of course to have a list of all streets of Karlsruhe, but this would make it harder to use the app in other cities

**Comment by daniel17903** [comment]
That's a great idea. I already thought about using some API like Google Maps for addresses. Using streets from our database might be a good alternative.

**Comment by skjerns** [comment]
implemented via #126

**Comment by daniel17903** [comment]
> implemented via #126

You can link PRs and issues by using this option on the right side of an issue or PR:
![image](https://user-images.githubusercontent.com/9028156/103765570-ab1cd800-501d-11eb-9611-fdc47bf81221.png)
