### ISSUE TITLE
Add button "Complete return"

### ISSUE THREAD

**Issue by skjerns** [leih-lokal/LeihLokalVerwaltung#111]
I think it would be useful to have a button with which a single click can return an item, maybe at the top of the RentalPopup? Would do the following things:

1. Set status on website to available
2. Set returned_on to today
3. set Pfand to full amount
4. Either prompt for kürzel or use recent one

**Comment by daniel17903** [comment]
That's a good idea. Maybe instead of a new Button in the popup we could also open a menu when right clicking a row for fast actions?

**Comment by skjerns** [comment]
we discussed that this should be in form of buttons, not right-click, as the second would be difficult to implement on a mobile phone, and less verbose/visible

**Comment by skjerns** [comment]
implemented!
