### ISSUE TITLE
Remove certain Inputs

### ISSUE THREAD

**Issue by skjerns** [leih-lokal/LeihLokalVerwaltung#139]
Now that we move away from excel we could think about dropping some of the things from there for keeping the UI cleaner.

I think the following could just be added as a Bemerkung, or dropped entirely:
- Pfand einbehalten (rental)
- Grund (rental)
- Verpackung (item)
- Anleitung (item)

"Pfand einbehalten" is something that can be infered anyway from "Pfand zurück" I guess? They have been added by someone in the last half year anyway, and I don't have the feeling they have been used consistently or are that useful after all.

What do you think?

**Comment by daniel17903** [comment]
I completely agree :)
