### ISSUE TITLE
Datepicker selects date from day before

### ISSUE THREAD

**Issue by skjerns** [leih-lokal/LeihLokalVerwaltung#203]
Since recently I have a strange bug: When I select a date, the datepicker returns the date from the day before, see gif.

Can you replicate this on your PCs?

![capture](https://user-images.githubusercontent.com/14980558/110101966-7ff80000-7da4-11eb-8597-d13315bcfdb9.gif)

**Comment by parttimenerd** [comment]
I cannot replicate it.

**Comment by skjerns** [comment]
Yes, strangely today it disappeared on my side as well.

**Comment by parttimenerd** [comment]
This could be the case. But we can then probably close this issue?

**Comment by daniel17903** [comment]
@skjerns I guess the first time you tried it between 0 and 1am? I think this is because the Datepicker always sets a timestamp at midnight (UTC+0) and your computer is set to UTC+1.

**Comment by skjerns** [comment]
Mhh, I made the issue at 11:18 AM, so not really :-/ but as it's dissappearing, I'll look into it again tomorrow ar 11:18 AM ;)

**Comment by daniel17903** [comment]
@skjerns I found it and fixed it. When selecting a date we didn't use the timezoneoffset for that date but for the current date. So when selecting a date in summertime (after 28.03.) the bug occured.

**Comment by skjerns** [comment]
Perfect! great job! Chris had the same issue yesterday, so good it's fixed now :)
