### ISSUE TITLE
Notifications/Display when item is available again

### ISSUE THREAD

**Issue by skjerns** [leih-lokal/LeihLokalVerwaltung#220]
Recently I have more and more requests from people asking when certain items are coming back. I think we did discuss this, but maybe it might be possible to add something

1) Add projected return date to the item site - this could be added as a formatted "special field" in WC, with a big disclaimer that there is no garantuee that items are indeed returned and are not late.
2) Alternatively add email reminders when items are back, that would probably be a bit more complicated to implement.

**Comment by skjerns** [comment]
I have two options to implement 1.

1) Just add it to the description field like the `Art-Nr` - this would be easier to implement and maintaine
2) Add a new custom field in WC, like `Pfand` - which is exclusively for showing projected return dates. I guess this would make it easier to enable/disable the field on demand

What do you think @daniel17903 ?

**Comment by daniel17903** [comment]
> I have two options to implement 1.
> 
> 1. Just add it to the description field like the `Art-Nr` - this would be easier to implement and maintaine
> 2. Add a new custom field in WC, like `Pfand` - which is exclusively for showing projected return dates. I guess this would make it easier to enable/disable the field on demand
> 
> What do you think @daniel17903 ?

I think both options could be implemented with low effort. If WC allows us to create an extra field and display it on the webpage I prefer option 2.

**Comment by skjerns** [comment]
Implemented!
