### ISSUE TITLE
Display warning if viewed on mobile

### ISSUE THREAD

**Issue by skjerns** [leih-lokal/LeihLokalVerwaltung#24]
On mobiles, currently just a blank page is being displayed. Might be good to display something like "cant be displayed on mobile" instead?

**Comment by daniel17903** [comment]
@skjerns which mobile OS and Browser did you test? On my mobile (Android 8 + Chrome Browser) it works.

A warning is still a good idea since the app is not optimized for small screens anyway.

**Comment by skjerns** [comment]
On iOS! Yeah, would be good to block it entirely I guess. Most phones still have a function to spoof for desktop browsers, that could be used if someone really needs to access it

**Comment by daniel17903** [comment]
@skjerns Ok, could you test if the notification works on your phone now? I succesfully tested it on an iPhone 7.

When switching to desktop mode the notification should disappear.

**Comment by skjerns** [comment]
mhh, strange it still stays blank on my iphone 6s. 

But I tested it with the devs toolbox in chrome, and it shows an error message there, so I guess the problem is with my smartphone
