### ISSUE TITLE
Match numbers exactly

### ISSUE THREAD

**Issue by skjerns** [leih-lokal/LeihLokalVerwaltung#27]
If I search for "100", I get all items that end with 100 as well, ie 2100 1005 100. Maybe it's possible to match exactly, if the input is strictly numerical?

I guess we need to take into account that with numbers one can look for item numbers, kundennummern or e.g. shoe sizes that are only annotated as string in the description

**Comment by daniel17903** [comment]
When searching for "100" I agree that we should not return 2100. But shouldn't we return 1001? In that case we should match from the beginning.

We could implement to match exactly or from the beginning for specified columns like id or deposit. For numbers contained in texts like shoe sizes this would not work but I think we could ignore that for now. We could fix that in the future by letting the user select columns to search.

**Comment by skjerns** [comment]
Mhh, I think ID should be matched exactly, at least if its below 3 digits. Imagine searching for number "6" and getting all 6XX, 6XXX. If conditional sorting like that is possible that would be optimal: if <3 digits: exact match, else match beginning.

**Comment by daniel17903** [comment]
Hm, I would still prefer match beginning. When searching for number "6" you would still get id 6 as first result. All other results would be listed below. In case you want to continue typing all possible ids are shown.

**Comment by skjerns** [comment]
Ah, okay, if the exact match is always displayed on top then no problem :) wocommerce doesn't do that, and that was always a bit annoying

**Comment by daniel17903** [comment]
@skjerns I think it works correctly now, could you test?

**Comment by skjerns** [comment]
seems to work, great!

in fringe-cases it might be that we look for item 25, but user 25 has 100s of rentals and will be displayed first. but i think there is no straigth forward way to prevent that except for column filtering, which has low priority i would say
