### ISSUE TITLE
Change rental item after saving -> change status of both items

### ISSUE THREAD

**Issue by skjerns** [leih-lokal/LeihLokalVerwaltung#450]
I found a reason why sometimes items are marked as "rented" when they are not:

1. When we create a rental, the item get's marked as "unavailable"
2. When we now see a mistake in the item number and open the rental and change it, the old item stays "unavailable", while the newly inserted item is correctly marked as "unavailable" as well

How could we fix this? Does the form have access to it's previous content?

**Comment by daniel17903** [comment]
Ah, great that you found this issue!
