### ISSUE TITLE
Save exact timestamp of creation

### ISSUE THREAD

**Issue by skjerns** [leih-lokal/LeihLokalVerwaltung#470]
Currently we save the timestamps for `rented_on`, `returned_on` and `extended_on` truncated to the start of the day. For statistics it would be very useful to change that to the exact timepoint and truncate the timestamp only when receiving it from the database.

1) That of course only works if the date of question is the current date/time. 
2) So maybe that does not work so easily, we could just have another variable `created` that saves the initial time, similar to `lastupdate`. 
3) Alternatively, we could change `lastupdate` to an array and append the date each time an update is made.

I poersonally like 3) most, what do you think @daniel17903  ?

**Comment by daniel17903** [comment]
Yes 3) should work. I think we currently do not use lastupdate for sorting anywhere so this shouldn‘t be a problem.
However, I would prefer 2) because its easier to implement and I think there is no need to save a timestamp for every change.
