### ISSUE TITLE
Fix `n+1` issues

### ISSUE THREAD

**Issue by muety** [leih-lokal/LeihLokalVerwaltung#509]
I just strolled through the code base for a bit and found a couple of places where individual requests are being made per every item in a list.

![Screenshot from 2023-04-13 22-17-02](https://user-images.githubusercontent.com/8978843/231880235-40dea70c-e143-49a5-a303-ca69a361a62c.png)

## Examples
Just to give a few examples:

https://github.com/leih-lokal/LeihLokalVerwaltung/blob/f35f5f8d734aff8fe3a014cd9c8e5eee6267df69/Frontend/src/data/rental/columns.js#L30-L37

☝️ Here, two requests are made for every rental, to fetch the highlighting colors for customer and item.

https://github.com/leih-lokal/LeihLokalVerwaltung/blob/f35f5f8d734aff8fe3a014cd9c8e5eee6267df69/Frontend/src/data/customer/columns.js#L134-L135

☝️ This one causes a request for every customer to get their number of rentals.

https://github.com/leih-lokal/LeihLokalVerwaltung/blob/f35f5f8d734aff8fe3a014cd9c8e5eee6267df69/Frontend/src/data/item/columns.js#L109

☝️ Similarly, this one fetches the number of rentals of every item one by one.

Fixing these would probably speed up the table. Low prio, though :v:.

Also, since I'm not familiar with CouchDB, I don't really know how to best get around these. Maybe using views? :thinking:

**Comment by skjerns** [comment]
That's a good one, thanks!

I think this is what's going on: The initial table is loaded with one request, and then, lot's of stuff is loaded async later with individual requests.

**Comment by muety** [comment]
Even worse, I found that almost every request is run at least twice in a row. 

![image](https://github.com/leih-lokal/LeihLokalVerwaltung/assets/8978843/bda816c4-2ecc-4693-a660-f1b0a207b612)

The ones with same request size also have the exact same body.
