### ISSUE TITLE
Minor: Increase autocomplete debounce delay

### ISSUE THREAD

**Issue by muety** [leih-lokal/LeihLokalVerwaltung#510]
While using the tool, I realized that, even if you type fairly fast, the autocomplete input keeps fetching suggestions from the database repeatedly. Because previous requests are not cancelled, they start queuing up, caused a weird flickering effect with the drop-down menu and unnecessarily slow down the database. I suggest to increase delay from 150 to 500 ms.

https://github.com/leih-lokal/LeihLokalVerwaltung/blob/f35f5f8d734aff8fe3a014cd9c8e5eee6267df69/Frontend/src/components/Input/AutocompleteInput.svelte#L27

![image](https://user-images.githubusercontent.com/8978843/232596140-2695e790-24f2-4296-8700-f38d1a6b8151.png)

**Comment by skjerns** [comment]
sounds good, lets do it! should not have any side effects I guess
