### ISSUE TITLE
Introduce new statuses

### ISSUE THREAD

**Issue by muety** [leih-lokal/LeihLokalVerwaltung#518]
Chris requested additional statuses:
* `lost` ("verschollen")
* `repairing` ("in Reparatur")
* `for_sale` ("Verkauf beim Flohmarkt")

**Comment by ColofoniusRegenschein** [comment]
Thanks @muety for opening this issue.

We must not forget to adapt the daily tasks scripts to the new statuses.
[Issue in Scripts](https://github.com/leih-lokal/scripts/issues/22)

**Comment by ColofoniusRegenschein** [comment]
The new statuses are additional to the existing on_backorder ("nicht verleihbar")
But they all set the on_backorder status in wooCommerce
