### ISSUE TITLE
Smaller improvements

### ISSUE THREAD

**Issue by skjerns** [leih-lokal/LeihLokalVerwaltung#93]
Some minor improvements I came along

- Make some fields not auto-complete (e.g. Telefonnummer, Hausnummer), Streetname is actually useful and we might think of including all streets in Karlsruhe as a default, so we don't have som many typos as currently.
- Maybe remember last volunteer kürzel for the day? or atleast suggest the least recent two?
- disable 'save' control after being pressed. I just pressed it accidentially twice and it gave me an error (however in the background all went correctly).

**Comment by christianstarck** [comment]
Also Customer E-Mails address shouldn't be auto-completable.
On the Laptop at Leihlokal it tends to write Dorotheas Address everytime someone clicks Karlsruhe as autocomplete for City.
