### ISSUE TITLE
Creating Items - multiple categories // add picture upload

### ISSUE THREAD

**Issue by christianstarck** [leih-lokal/LeihLokalVerwaltung#95]
- Some Items, like a mini Oven, can have multiple Categories (Household and Kitchen). But it's not possible to select more than on Category when adding an Item.
- The Input for a Picture does not have any action, like upload or to choose a Path.

**Comment by skjerns** [comment]
How is the category saved @daniel17903 ? I think it is finally synchronized to WordPress, right? And there we can only have one category I think... but let's check this

**Comment by daniel17903** [comment]
The category is saved in couchdb and then also synchronized to WordPress. On WordPress multiple categories are possible. We just need to adapt the client code, at the moment only one category can be synchronized.

**Comment by daniel17903** [comment]
Now multiple categories can be selected and synchronized. Picture upload is still missing.

**Comment by daniel17903** [comment]
I am closing this since we have another issue for picture upload #234
