### ISSUE TITLE
Create Leihvorgang improvements

### ISSUE THREAD

**Issue by christianstarck** [leih-lokal/LeihLokalVerwaltung#98]
1. Surround User and Item search fields with wildcards. 
-- Burger should find Hamburgerformer and Ustermann should find Mustermann 
2. Show additional Userinfo like Id Number, Firstname, Street and House Number in the autocomplete drop-down.
-- Would make it easier to find the right Person if there are Last Name doublets. 
3. Add Users Phone Number and Address Field.
-- If one is missing this would make it easier to notice and add the info.
4. Show Item Status and Id Number in the autocomplete drop-down.
-- Easier to pick the correct Raclette ;)
5. Let user pick new Website Status instead of just say "Update status on web page".
-- Easier to make sure Drill stay available.
-- Is it possible to autoselect available if a return date is added?

**Comment by daniel17903** [comment]
1. Should already work in this way
2. I think there is not enough space to display everything and it would decrease the number of users visible in the dropdown. Maybe we could try to display one additional attribute
3. I do think you are right, we should somehow make it visible to the user if important information is missing. I do not think that we should add these fields to edit user data in the rental popup. Maybe we could instead display a warning and a link to edit the user.
4. That's a good point
5. At the moment, when "Update status on web page" is checked, the item is set to "not available" when a new rental is created or set to "available" when a rental ended (return date <= today). Let the user pick a status might be easier to understand.

**Comment by christianstarck** [comment]
1. Unfortunately not
2. Then the First Name should also be visible I think. 
3. Sounds good to me.
5. Thanks for clarification. That's fine then.

**Comment by daniel17903** [comment]
**Done:**
2. Now we show id, firstname and lastname
3. See #100 
4. Id is included now

**Still Todo:**
1. For the Autocomplete fields we will keep searching from the beginning. For items we will add synonyms to the database (e.g. when searching for "säge" we could also find "Dekupiersäge").
5. We will do that

**Comment by skjerns** [comment]
1. it will already find `Dekupiersäge` if we enter `säge`!

**Comment by daniel17903** [comment]
**Done:**

- Synonyms exist in the Database

**Still Todo:**

- Also search for synonyms when inserting an item name in RentalPopupFormular
