### ISSUE TITLE
Shopping Cart

### ISSUE THREAD

**Issue by christianstarck** [leih-lokal/LeihLokalVerwaltung#99]
This is an idea you can think about. It is quickly explained and helpful for the Volunteers but I do think a sh**load of work.

For Leihvorgänge with more than one Item it would be much easier to be able to add a Costumer and Items to a Shopping Card.
When the Costumer got all it's Items just press finish Leihvorgang and all items will be borrowed.

What do you think of this?

**Comment by daniel17903** [comment]
Thats a nice idea.

**Comment by skjerns** [comment]
superseeded by #225
